apiVersion: apps/v1
kind: Deployment 
metadata:
 name: postgres-deployment
 labels: 
  name: postgres-deployment
  app: web-app
spec:
 replicas: 2
 selector:
  matchLabels:
    name: postgres-pod
    app: web-app
 template:
  metadata:
   name: postgres-pod
   labels: 
    name: postgres-pod
    app: web-app
  spec:
   containers:
    - name: db-app
      image: postgres
      ports:
       - containerPort: 5432
      resources:
       limits:
        memory: "128Mbi"
        cpu: "500m"  
      env:
        - name:  POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"      
