apiVersion: apps/v1
kind: Deployment 
metadata:
 name: result-app-deployment
 labels: 
  name: result-app-deployment
  app: web-app
spec: 
 replicas: 2
 selector: 
  matchLabels:
    name: result-app-node
    app: web-app
 template: 
  metadata:
    name: result-app-node
    labels:
      name: result-app-node
      app: web-app
    spec:
    containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80  
      
