apiVersion: v1
kind: Service
metadata:
 name: result-service
 labels:
  name: result-service
  app: web-app
spec:
 type: NodePort
 ports: 
 - port: 80
   targetPort: 80
   nodePort: 32006
 selector:
  name: result-app-node
  app: web-app    