apiVersion: v1
kind: Pod
metadata: 
 name: voting-app
 labels:
  name: voting-app
  app: web-app
spec:
 containers:
  - name: voting-app
    image: lugardesosa/vote:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80