apiVersion: v1
kind: Service 
metadata:
 name: voting-app-service
 labels:
  name: voting-app
  app: web-app
spec:
 type: NodePort 
 ports: 
  - port: 80
    targetPort: 80
    nodePort: 30005
 selector:  
  name: voting-app
  app: web-app